### ISSUE TITLE
lateinit property redirectUriResult has not been initialized

### ISSUE THREAD

**Issue by probepark** [kakao/kakao_flutter_sdk#109]
How can i fix this problem?

```
Caused by b9.u: lateinit property redirectUriResult has not been initialized
       at com.kakao.sdk.flutter.KakaoFlutterSdkPlugin$Companion.getRedirectUriResult(KakaoFlutterSdkPlugin.java:7)
       at com.kakao.sdk.flutter.TalkAuthCodeActivity.onActivityResult(TalkAuthCodeActivity.java:47)
       at android.app.Activity.dispatchActivityResult(Activity.java:8120)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4983)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5031)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2063)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7615)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

I'm using  kakao_flutter_sdk: 0.8.1, appId is 2501

**Comment by mbkim95** [comment]
Hello

More information is needed to identify issues.

Please write down the device where the issue occurred and the exact date and time when the issue occurred.

**Comment by probepark** [comment]
date : 2021. 10. 4. 오후 7:15:18
os version : android 11
model : Galaxy A30

깃헙인데 영어로 해야할 거 같아서..ㅋㅋ 많이 부족했나요

**Comment by mbkim95** [comment]
그런 의미는 아니였고, 앱 정보와 이슈 디바이스 로그 남겨두신걸보니 한국분인 것으로 보여 한글이 서로 의사소통하기 더 편할 것 같아서 말씀드렸습니다ㅎㅎ

제보주신 2개의 이슈 모두 전혀 재현되지 않아서 정확한 원인을 파악하지 못하고 있네요ㅠㅠ

혹시 프로젝트 파일 공유가 가능할까요? 코드를 공유해주신다면 조금 더 수월하게 이슈를 파악할 수 있을 것 같습니다.

공유가 가능하시다면 mbkim95@naver.com 으로 파일 공유해주시면 감사하겠습니다.
