### ISSUE TITLE
Null' is not a subtype of type 'Map<String, dynamic>' in type cast

### ISSUE THREAD

**Issue by kghoon** [kakao/kakao_flutter_sdk#112]
```
I/flutter (18716): #0      _$TotalAddressFromJson      package:kakao_flutter_sdk/…/model/total_address.g.dart:16
I/flutter (18716): #1      new TotalAddress.fromJson.    package:kakao_flutter_sdk/…/model/total_address.dart:23
I/flutter (18716): #2      GenericsConverter.fromJson.    package:kakao_flutter_sdk/…/local/generics_converter.dart:25
I/flutter (18716): #3      _$LocalEnvelopeFromJson.<anonymous closure>.         package:kakao_flutter_sdk/…/model/local_envelope.g.dart:13
I/flutter (18716): #4      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
I/flutter (18716): #5      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
I/flutter (18716): #6      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
I/flutter (18716): #7      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
I/flutter (18716): #8      new List.of (dart:core-patch/array_patch.dart:50:28)
I/flutter (18716): #9      ListIterable.toList (dart:_internal/iterable.dart:213:44)
I/flutter (18716): #10     _$LocalEnvelopeFromJson
package:kakao_flutter_sdk/…/model/local_envelope.g.dart:14

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'List<TotalAddress>' in type cast
```

JSON decode 하다가 에러가 발생합니다.
flutter_kakao_sdk 0.8.2 를 사용 중입니다.

**Comment by mbkim95** [comment]
안녕하세요

에러가 발생한 코드와 앱 id 첨부 부탁드려요

**Comment by kghoon** [comment]
문제가 되는 부분의 코드입니다.

```
    final address = await await LocalApi.instance.address(keyword, page: 1, size: 30);
    List<TotalAddress>? totalAddressList =
        address?.documents as List<TotalAddress>;
```


앱ID는 553391 입니다.

**Comment by mbkim95** [comment]
이슈 재현되는 것 확인했습니다.

이슈 수정된 버전은 이번주 중으로 배포하도록 하겠습니다.

제보 감사합니다

**Comment by mbkim95** [comment]
@kghoon 이슈 수정된 0.9.0 버전 릴리즈 되었습니다.
