### ISSUE TITLE
[Question] authorize() 호출 시 앱 재실행 현상

### ISSUE THREAD

**Issue by tazan83** [kakao/kakao_flutter_sdk#160]
### 문의 사항 (Question)

안녕하세요.
카카오톡 미설치 시 카카오 로그인을 위해 AuthCodeClient.instance.authorize() 호출하고 있습니다.
해당 함수 호출 시 앱이 재실행되는 현상이 있어 문의 드립니다.

사용 버전 정보는 아래와 같습니다.
- Flutter version 2.10.5
- Dart version 2.16.2
- kakao_flutter_sdk 1.3.0

**[AndroidManifest.xml]**
```
<activity android:name="com.kakao.sdk.flutter.AuthCodeCustomTabsActivity">
    <intent-filter android:label="flutter_web_auth">
        <action android:name="android.intent.action.VIEW" />

        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />

        <data
            android:host="oauth"
            android:scheme="@string/kakao_scheme" />
    </intent-filter>
</activity>
```

**[styles.xml]**
```
<style name="LaunchTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
</style>
```

**[로그]**
```
W/ActivityThread(18869): handleWindowVisibility: no activity for token android.os.BinderProxy@2ca2438
E/GeneratedPluginRegistrant(18869): Error registering plugin flutter_naver_login, com.yoonjaepark.flutter_naver_login.FlutterNaverLoginPlugin
E/GeneratedPluginRegistrant(18869): java.lang.ClassCastException: com.kakao.sdk.flutter.AuthCodeCustomTabsActivity cannot be cast to io.flutter.embedding.android.FlutterFragmentActivity
E/GeneratedPluginRegistrant(18869): 	at com.yoonjaepark.flutter_naver_login.FlutterNaverLoginPlugin.onAttachedToActivity(FlutterNaverLoginPlugin.kt:114)
E/GeneratedPluginRegistrant(18869): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:155)
E/GeneratedPluginRegistrant(18869): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:74)
E/GeneratedPluginRegistrant(18869): 	at java.lang.reflect.Method.invoke(Native Method)
E/GeneratedPluginRegistrant(18869): 	at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80)
E/GeneratedPluginRegistrant(18869): 	at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:1009)
E/GeneratedPluginRegistrant(18869): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:199)
E/GeneratedPluginRegistrant(18869): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:459)
E/GeneratedPluginRegistrant(18869): 	at com.kakao.sdk.flutter.AuthCodeCustomTabsActivity.onCreate(AuthCodeCustomTabsActivity.kt:19)
E/GeneratedPluginRegistrant(18869): 	at android.app.Activity.performCreate(Activity.java:7963)
E/GeneratedPluginRegistrant(18869): 	at android.app.Activity.performCreate(Activity.java:7952)
E/GeneratedPluginRegistrant(18869): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
E/GeneratedPluginRegistrant(18869): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
E/GeneratedPluginRegistrant(18869): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
E/GeneratedPluginRegistrant(18869): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
E/GeneratedPluginRegistrant(18869): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/GeneratedPluginRegistrant(18869): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/GeneratedPluginRegistrant(18869): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
E/GeneratedPluginRegistrant(18869): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/GeneratedPluginRegistrant(18869): 	at android.os.Looper.loop(Looper.java:237)
E/GeneratedPluginRegistrant(18869): 	at android.app.ActivityThread.main(ActivityThread.java:8167)
E/GeneratedPluginRegistrant(18869): 	at java.lang.reflect.Method.invoke(Native Method)
E/GeneratedPluginRegistrant(18869): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/GeneratedPluginRegistrant(18869): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
D/PhoneWindow(18869): forceLight changed to true [] from com.android.internal.policy.PhoneWindow.updateForceLightNavigationBar:4274 com.android.internal.policy.DecorView.updateColorViews:1547 com.android.internal.policy.PhoneWindow.dispatchWindowAttributesChanged:3252 android.view.Window.setFlags:1153 com.android.internal.policy.PhoneWindow.generateLayout:2474
I/MultiWindowDecorSupport(18869): [INFO] isPopOver = false
I/MultiWindowDecorSupport(18869): updateCaptionType >> DecorView@de2899[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
D/MultiWindowDecorSupport(18869): setCaptionType = 0, DecorView = DecorView@de2899[]
D/CustomTabsCommonClient(18869): Choosing com.android.chrome as custom tabs browser
I/ViewRootImpl@973b7d3[AuthCodeCustomTabsActivity](18869): setView = com.android.internal.policy.DecorView@de2899 TM=true MM=false
I/ViewRootImpl@ec6eff1[MainActivity](18869): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(18869): prepareNavigationBarInfo() DecorView@229e113[MainActivity]
D/InputMethodManager(18869): getNavigationBarColor() -657931
I/SurfaceView(18869): onWindowVisibilityChanged(0) true io.flutter.embedding.android.FlutterSurfaceView{55b5141 V.E...... ......I. 0,0-0,0} of ViewRootImpl@973b7d3[AuthCodeCustomTabsActivity]
I/ViewRootImpl@973b7d3[AuthCodeCustomTabsActivity](18869): Relayout returned: old=(0,0,1440,2960) new=(0,0,1440,2960) req=(1440,2960)0 dur=9 res=0x7 s={true 530239393792} ch=true
I/mali_winsys(18869): new_window_surface() [1440x2960] return: 0x3000
I/SurfaceView(18869): surfaceCreated 1 #8 io.flutter.embedding.android.FlutterSurfaceView{55b5141 V.E...... ......ID 0,0-1440,2768}
I/mali_winsys(18869): new_window_surface() [1440x2768] return: 0x3000
I/SurfaceView(18869): surfaceChanged (1440,2768) 1 #8 io.flutter.embedding.android.FlutterSurfaceView{55b5141 V.E...... ......ID 0,0-1440,2768}
I/ViewRootImpl@973b7d3[AuthCodeCustomTabsActivity](18869): Relayout returned: old=(0,0,1440,2960) new=(0,0,1440,2960) req=(1440,2960)0 dur=4 res=0x3 s={true 530239393792} ch=false
I/ViewRootImpl@973b7d3[AuthCodeCustomTabsActivity](18869): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(18869): prepareNavigationBarInfo() DecorView@de2899[AuthCodeCustomTabsActivity]
D/InputMethodManager(18869): getNavigationBarColor() -855310
D/InputMethodManager(18869): prepareNavigationBarInfo() DecorView@de2899[AuthCodeCustomTabsActivity]
D/InputMethodManager(18869): getNavigationBarColor() -855310
V/InputMethodManager(18869): Starting input: tba=com.test.abc.dev ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(18869): startInputInner - Id : 0
I/InputMethodManager(18869): startInputInner - mService.startInputOrWindowGainedFocus
I/ViewRootImpl@973b7d3[AuthCodeCustomTabsActivity](18869): MSG_RESIZED_REPORT: frame=(0,0,1440,2960) ci=(0,96,0,192) vi=(0,96,0,192) or=1
I/ViewRootImpl@973b7d3[AuthCodeCustomTabsActivity](18869): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(18869): prepareNavigationBarInfo() DecorView@de2899[AuthCodeCustomTabsActivity]
D/InputMethodManager(18869): getNavigationBarColor() -855310
I/SurfaceView(18869): onWindowVisibilityChanged(8) false io.flutter.embedding.android.FlutterSurfaceView{55b5141 V.E...... ......ID 0,0-1440,2768} of ViewRootImpl@973b7d3[AuthCodeCustomTabsActivity]
I/SurfaceView(18869): surfaceDestroyed callback.size 1 #2 io.flutter.embedding.android.FlutterSurfaceView{55b5141 V.E...... ......ID 0,0-1440,2768}
I/mali_egl(18869): eglDestroySurface() in
I/mali_winsys(18869): delete_surface() [1440x2768] return
I/mali_egl(18869): eglDestroySurface() out
W/libEGL  (18869): EGLNativeWindowType 0x7bc2d2b010 disconnect failed
I/SurfaceView(18869): remove() io.flutter.embedding.android.FlutterSurfaceView{55b5141 V.E...... ......ID 0,0-1440,2768} Surface(name=SurfaceView - com.test.abc.dev/com.kakao.sdk.flutter.AuthCodeCustomTabsActivity@55b5141@0)/@0x8283b72
I/mali_egl(18869): eglDestroySurface() in
I/mali_winsys(18869): delete_surface() [1440x2960] return
I/mali_egl(18869): eglDestroySurface() out
W/libEGL  (18869): EGLNativeWindowType 0x7c7c6d0f90 disconnect failed
I/ViewRootImpl@973b7d3[AuthCodeCustomTabsActivity](18869): Relayout returned: old=(0,0,1440,2960) new=(0,0,1440,2960) req=(1440,2960)8 dur=4 res=0x5 s={false 0} ch=true
D/InputTransport(18869): Input channel destroyed: 'ClientS', fd=176
I/ViewRootImpl@973b7d3[AuthCodeCustomTabsActivity](18869): stopped(true) old=false
I/SurfaceView(18869): windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{55b5141 V.E...... ......ID 0,0-1440,2768} of ViewRootImpl@973b7d3[AuthCodeCustomTabsActivity]
I/mali_egl(18869): eglDestroySurface() in
I/mali_winsys(18869): delete_surface() [1440x2960] return
I/mali_egl(18869): eglDestroySurface() out
W/libEGL  (18869): EGLNativeWindowType 0x7c7c6d0310 disconnect failed
I/ViewRootImpl@ec6eff1[MainActivity](18869): Relayout returned: old=(0,0,1440,2960) new=(0,0,1440,2960) req=(1440,2960)8 dur=6 res=0x5 s={false 0} ch=true
I/ViewRootImpl@ec6eff1[MainActivity](18869): stopped(true) old=false
D/abxrm   (18869): AdBrixRm is already initialized
D/ConnectivityManager(18869): requestNetwork; CallingUid : 10701, CallingPid : 18869
D/InputMethodManager(18869): HSIFW - flag : 0
W/FA      (18869): Cannot log screen view event when the app is in the background.
D/PhoneWindow(18869): forceLight changed to false [com.test.abc.dev/com.kakao.sdk.flutter.AuthCodeCustomTabsActivity] from com.android.internal.policy.PhoneWindow.updateForceLightNavigationBar:4280 com.android.internal.policy.PhoneWindow.setNavigationBarColor:4102 io.flutter.plugin.platform.PlatformPlugin.setSystemChromeSystemUIOverlayStyle:428 io.flutter.plugin.platform.PlatformPlugin.access$700:30 io.flutter.plugin.platform.PlatformPlugin$1.setSystemUiOverlayStyle:108
I/ViewRootImpl@973b7d3[AuthCodeCustomTabsActivity](18869): Relayout returned: old=(0,0,1440,2960) new=(0,0,1440,2960) req=(1440,2960)8 dur=12 res=0x1 s={false 0} ch=false
I/flutter (18869):
```

**Comment by mbkim95** [comment]
안녕하세요

에러 로그를 확인해봤을 때는 사용하고 계신 flutter_naver_login 패키지에서 에러가 발생하는 것으로 보여서 해당 패키지 쪽에 문의가 필요할 것 같아요.

그리고 이슈와 별개로 카카오톡 계정 로그인을 하시려면 [공식 문서](https://developers.kakao.com/docs/latest/ko/kakaologin/flutter#login-with-kakaoaccount) 참고하셔서 `UserApi.instance.loginWithKakaoAccount()` 를 사용하시고 [공식 문서](https://developers.kakao.com/docs/latest/ko/kakaologin/flutter#before-you-begin-android) 참고하셔서 AndroidManifest.xml 파일에 AuthCodeCustomTabsActivity 를 등록할 때 `android:exported="true"` 추가 부탁드립니다.

**Comment by tazan83** [comment]
답변 감사합니다.

알려주신 사용법으로 해보았으나 여전히 발생하여 example 기준으로 테스트 해본 결과,
아래와 같은 로그를 확인했습니다. 

리스트 내 loginWithKakaoAccount() 선택 > "카카오계정으로 간편가입" 화면 진입 시
MyApp이 다시 빌드 되는 것 같습니다.

혹시 이 현상이 정상인지 추가 문의 드립니다.

```
Launching lib/main.dart on SM N960N in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
I/flutter.exampl(11491): Late-enabling -Xcheck:jni
E/flutter.exampl(11491): Unknown bits set in runtime_flags: 0x8000
W/flutter.exampl(11491): Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (greylist, reflection, allowed)
W/flutter.exampl(11491): Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (greylist, reflection, allowed)
W/flutter.exampl(11491): Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (greylist, reflection, allowed)
W/flutter.exampl(11491): Accessing hidden method Landroid/util/LongArray;->get(I)J (greylist, reflection, allowed)
Connecting to VM Service at ws://127.0.0.1:53412/vqAUxE3wOyw=/ws
**I/flutter (11491): =====MyApp build=======
I/flutter (11491): =====MainPage build====**
W/Gralloc3(11491): mapper 3.x is not supported
I/gralloc (11491): Arm Module v1.0
I/OpenGLRenderer(11491): doUpdatePositionAsync is called and callVoidMethod
I/ViewRootImpl@f66654e[MainActivity](11491): ViewPostIme pointer 0
I/ViewRootImpl@f66654e[MainActivity](11491): ViewPostIme pointer 1
[log] [🔬] https://kauth.kakao.com/oauth/authorize?client_id=030ba7c59137629e86e8721eb1a22fd6&redirect_uri=kakao030ba7c59137629e86e8721eb1a22fd6%3A%2F%2Foauth&response_type=code&codeChallenge=czprQutp%2BNbAW5lPfYS%2BxjT7ZDmaQNZET%2F2nKELBocA%3D&codeChallengeMethod=S256&ka=sdk%2F1.3.1+sdk_type%2Fflutter+os%2Fandroid-29+lang%2Fko-KR+origin%2FhpUC0U1l9dfmHv1uv4da1W6fcjI%3D+device%2FSM-N960N+android_pkg%2Fcom.kakao.sdk.flutter.example+app_ver%2F1.3.1
W/ActivityThread(11491): handleWindowVisibility: no activity for token android.os.BinderProxy@36a4a6b
D/PhoneWindow(11491): forceLight changed to true [] from com.android.internal.policy.PhoneWindow.updateForceLightNavigationBar:4274 com.android.internal.policy.DecorView.updateColorViews:1547 com.android.internal.policy.PhoneWindow.dispatchWindowAttributesChanged:3252 android.view.Window.setFlags:1153 com.android.internal.policy.PhoneWindow.generateLayout:2474
I/MultiWindowDecorSupport(11491): [INFO] isPopOver = false
I/MultiWindowDecorSupport(11491): updateCaptionType >> DecorView@f405b10[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
D/MultiWindowDecorSupport(11491): setCaptionType = 0, DecorView = DecorView@f405b10[]
D/CustomTabsCommonClient(11491): Choosing com.android.chrome as custom tabs browser
I/ViewRootImpl@8953d41[AuthCodeCustomTabsActivity](11491): setView = com.android.internal.policy.DecorView@f405b10 TM=true MM=false
I/ViewRootImpl@f66654e[MainActivity](11491): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(11491): prepareNavigationBarInfo() DecorView@91d1d76[MainActivity]
D/InputMethodManager(11491): getNavigationBarColor() -855310
I/SurfaceView(11491): onWindowVisibilityChanged(0) true io.flutter.embedding.android.FlutterSurfaceView{50d5027 V.E...... ......I. 0,0-0,0} of ViewRootImpl@8953d41[AuthCodeCustomTabsActivity]
I/ViewRootImpl@8953d41[AuthCodeCustomTabsActivity](11491): Relayout returned: old=(0,0,1440,2960) new=(0,0,1440,2960) req=(1440,2960)0 dur=9 res=0x7 s={true 527995236352} ch=true
I/mali_winsys(11491): new_window_surface() [1440x2960] return: 0x3000
I/SurfaceView(11491): surfaceCreated 1 #8 io.flutter.embedding.android.FlutterSurfaceView{50d5027 V.E...... ......ID 0,0-1440,2768}
I/mali_winsys(11491): new_window_surface() [1440x2768] return: 0x3000
I/SurfaceView(11491): surfaceChanged (1440,2768) 1 #8 io.flutter.embedding.android.FlutterSurfaceView{50d5027 V.E...... ......ID 0,0-1440,2768}
I/ViewRootImpl@8953d41[AuthCodeCustomTabsActivity](11491): Relayout returned: old=(0,0,1440,2960) new=(0,0,1440,2960) req=(1440,2960)0 dur=9 res=0x3 s={true 527995236352} ch=false
I/ViewRootImpl@8953d41[AuthCodeCustomTabsActivity](11491): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(11491): prepareNavigationBarInfo() DecorView@f405b10[AuthCodeCustomTabsActivity]
D/InputMethodManager(11491): getNavigationBarColor() -855310
D/InputMethodManager(11491): prepareNavigationBarInfo() DecorView@f405b10[AuthCodeCustomTabsActivity]
D/InputMethodManager(11491): getNavigationBarColor() -855310
V/InputMethodManager(11491): Starting input: tba=com.kakao.sdk.flutter.example ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(11491): startInputInner - Id : 0
I/InputMethodManager(11491): startInputInner - mService.startInputOrWindowGainedFocus
I/ViewRootImpl@8953d41[AuthCodeCustomTabsActivity](11491): MSG_RESIZED_REPORT: frame=(0,0,1440,2960) ci=(0,96,0,192) vi=(0,96,0,192) or=1
I/ViewRootImpl@8953d41[AuthCodeCustomTabsActivity](11491): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(11491): prepareNavigationBarInfo() DecorView@f405b10[AuthCodeCustomTabsActivity]
D/InputMethodManager(11491): getNavigationBarColor() -855310
D/InputTransport(11491): Input channel destroyed: 'ClientS', fd=90
I/SurfaceView(11491): onWindowVisibilityChanged(8) false io.flutter.embedding.android.FlutterSurfaceView{50d5027 V.E...... ......ID 0,0-1440,2768} of ViewRootImpl@8953d41[AuthCodeCustomTabsActivity]
I/SurfaceView(11491): surfaceDestroyed callback.size 1 #2 io.flutter.embedding.android.FlutterSurfaceView{50d5027 V.E...... ......ID 0,0-1440,2768}
I/mali_egl(11491): eglDestroySurface() in
I/mali_winsys(11491): delete_surface() [1440x2768] return
I/mali_egl(11491): eglDestroySurface() out
W/libEGL  (11491): EGLNativeWindowType 0x7ac5cbc010 disconnect failed
I/SurfaceView(11491): remove() io.flutter.embedding.android.FlutterSurfaceView{50d5027 V.E...... ......ID 0,0-1440,2768} Surface(name=SurfaceView - com.kakao.sdk.flutter.example/com.kakao.sdk.flutter.AuthCodeCustomTabsActivity@50d5027@0)/@0xf376c7d
I/mali_egl(11491): eglDestroySurface() in
I/mali_winsys(11491): delete_surface() [1440x2960] return
I/mali_egl(11491): eglDestroySurface() out
W/libEGL  (11491): EGLNativeWindowType 0x7d0b198a10 disconnect failed
I/ViewRootImpl@8953d41[AuthCodeCustomTabsActivity](11491): Relayout returned: old=(0,0,1440,2960) new=(0,0,1440,2960) req=(1440,2960)8 dur=5 res=0x5 s={false 0} ch=true
I/ViewRootImpl@8953d41[AuthCodeCustomTabsActivity](11491): stopped(true) old=false
I/SurfaceView(11491): windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{50d5027 V.E...... ......ID 0,0-1440,2768} of ViewRootImpl@8953d41[AuthCodeCustomTabsActivity]
I/SurfaceView(11491): onWindowVisibilityChanged(8) false io.flutter.embedding.android.FlutterSurfaceView{4876844 V.E...... ........ 0,0-1440,2768} of ViewRootImpl@f66654e[MainActivity]
I/SurfaceView(11491): surfaceDestroyed callback.size 1 #2 io.flutter.embedding.android.FlutterSurfaceView{4876844 V.E...... ........ 0,0-1440,2768}
I/mali_egl(11491): eglDestroySurface() in
I/mali_winsys(11491): delete_surface() [1440x2768] return
I/mali_egl(11491): eglDestroySurface() out
W/libEGL  (11491): EGLNativeWindowType 0x7af8bbb010 disconnect failed
I/SurfaceView(11491): remove() io.flutter.embedding.android.FlutterSurfaceView{4876844 V.E...... ........ 0,0-1440,2768} Surface(name=SurfaceView - com.kakao.sdk.flutter.example/com.kakao.sdk.flutter.example.MainActivity@4876844@0)/@0x9f4c7c3
I/mali_egl(11491): eglDestroySurface() in
I/mali_winsys(11491): delete_surface() [1440x2960] return
I/mali_egl(11491): eglDestroySurface() out
W/libEGL  (11491): EGLNativeWindowType 0x7d0b19bad0 disconnect failed
I/ViewRootImpl@f66654e[MainActivity](11491): Relayout returned: old=(0,0,1440,2960) new=(0,0,1440,2960) req=(1440,2960)8 dur=8 res=0x5 s={false 0} ch=true
I/ViewRootImpl@f66654e[MainActivity](11491): stopped(true) old=false
I/SurfaceView(11491): windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{4876844 V.E...... ........ 0,0-1440,2768} of ViewRootImpl@f66654e[MainActivity]
**I/flutter (11491): =====MyApp build=======
I/flutter (11491): =====MainPage build====**
```

**Comment by mbkim95** [comment]
말씀주신 내용에 대해서 확인해봤는데 1.3.0 버전부터 안드로이드 환경에서 재현되는 것 확인했습니다.

안드로이드 환경에서 `UserApi.instance.loginWithKakaoAccount()`를 호출하게 되면 AuthCodeCustomTabActivity가 실행됩니다. 그런데 해당Activity는 FlutterActivity 클래스를 상속하고 있고, FlutterActivity는 내부적으로 main 함수를 실행시키기 때문에 main 함수가 중복해서 호출되는 이슈가 발생했습니다.
참고: https://api.flutter.dev/javadoc/io/flutter/embedding/android/FlutterActivity.html

말씀주신 이슈는 수정해서 설 연휴 이후에 최대한 빠르게 배포하도록 하겠습니다.

이슈 제보주셔서 감사합니다

**Comment by mbkim95** [comment]
@tazan83 
안녕하세요 해당 이슈 수정된 1.4.0 버전 배포완료되었습니다.
제보주셔서 다시 한번 감사드립니다
