### ISSUE TITLE
[Bug] 카카오톡 로그인 이후 카메라 촬영시 앱 팅김 현상

### ISSUE THREAD

**Issue by Funncy** [kakao/kakao_flutter_sdk#161]
### 이슈 설명 (Issue description)

현재 저는 React로 만들어진 web을 Flutter로 래핑하는 작업을 하고 있습니다.
React에서 카카오톡 로그인은 Flutter를 통해서 Native를 호출하도록 구현하였고 kakao_flutter_sdk 라이브러리를 통해 잘 구현하였습니다.
그런데 갑자기 잘 되던 카메라 촬영에서 앱이 팅기는 현상이 발생하였고, 버그를 재현하던 중 카카오톡 로그인 이후에만 발생하는 것을 확인하였습니다.

android studio로 디버그를 해보니 KakaoFlutterSDKPlugin.kt 201번 라인에서 계속 앱이 죽었고
순서대로 코드를 실행해보니 카카오톡 로그인떄 정상적인 흐름을 타는데 카메라 촬영이후 앱으로 돌아오면 다시 onActivityResult 함수가 빈 내용으로 실행되어 에러가 발생합니다. 

카카오톡 로그인이 이미 되있는 상태로 앱을 껏다가 키면 정상동작하고 onActivityResult 함수가 호출되지 않습니다.

아래는 에러 로그입니다.

D/AndroidRuntime( 3420): Shutting down VM
E/AndroidRuntime( 3420): FATAL EXCEPTION: main
E/AndroidRuntime( 3420): Process: com. heroines .heroines, PID: 3420
E/AndroidRuntime( 3420): java. lang. RuntimeException: Failure delivering result ResultInfo {who-null, request 1, result -1, data-null} to activity {com.heroines. heroines/com. heroines. heroines MainActivity}: java.'
E/AndroidRuntime( 3420):
at android.app.ActivityThread. deliverResults(ActivityThread. java:5360)
E/AndroidRuntime( 3420):
at android.app.ActivityThread.handleSendResult(ActivityThread.java:5401)
E/AndroidRuntime( 3420):
at android. app .servertransaction.ActivityResultItem. execute(ActivityResultItem. java:51)
E/AndroidRuntime ( 3420):
at android.app. servertransaction. TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 3420):
at android. app. servertransaction. TransactionExecutor, execute(TransactionExecutor. java:95)
E/AndroidRuntime( 3420):
at android.app.ActivityThreadSH. handLeMessage(ActivityThread. java: 2267)
E/AndroidRuntime( 3420):
at android. os. Handler. dispatchMessage(Handler. java: 107)
E/AndroidRuntime( 3420):
at android.os. Looper. Loop (Looper. java: 237)
E/AndroidRuntime( 3420):
at android.app.ActivityThread.main(ActivityThread. java: 8167)
E/AndroidRuntime( 3420):
at java. lang. reflect.Method. invoke(Native Method)
E/AndroidRuntime( 3420):
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/AndroidRuntime( 3420):
at com.android. internal.os.ZygoteInit.main(ZygoteInit. java:1100)
E/AndroidRuntime( 3420): Caused by: java. Lang. IlLegalStateException: Reply already submitted
E/AndroidRuntime( 3420):
at to. flutter, embedding. engine. dart. DartMessenger$Reply. reply(DartMessenger, java: 430)
E/AndroidRuntime( 3420):
at o. flutter .plugin. common .MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
E/AndroidRuntime( 3420):
at com. kakao. sdk. flutter . KakaoFlutterSdkPlugin.onActivityResult(KakaoFlutterSdkPlugin.kt:201)
E/AndroidRuntime( 3420):
at io. flutter .embedding. engine. FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FLutterEngineConnectionRegistry.java:805)
E/AndroidRuntime ( 3420):
at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FLutterEngineConnectionRegistry.java:428)
E/AndroidRuntime( 3420):
at io. flutter. embedding. android. FlutterActivityAndFragmentDelegate. onActivityResult(FLutterActivityAndFragmentDelegate.java:807)
E/AndroidRuntime( 3420):
at io.flutter.embedding.android. FlutterActivity.onActivityResult(FlutterActivity. java: 724)
E/AndroidRuntime( 3420):
at android.app.Activity.dispatchActivityResult(Activity. java: 8300)
E/AndroidRuntime( 3420):
at android.app.ActivityThread.deliverResults(ActivityThread. java:5353)
E/AndroidRuntime( 3420):
..11 more

### 앱 ID (App ID)

760989

### 플랫폼 (Platform)

Android 10

### 디바이스 (Device)

SM-N960N 

### Version

1.3.0

### Flutter SDK

3.3.9

### 재현 방법 (Steps to reproduce)

1. 카카오톡 로그인 진행 (onActivityResult이 함수가 한번 호출된 상태) 
2. webview에서 input type=file을 통해 카메라 촬영
3. 카메라 촬영 이후 앱으로 다시 돌아오면 앱이 죽음

### Logs

```shell
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=null} to activity {com.heroines.heroines/com.heroines.heroines.MainActivity}: java.lang.IllegalStateException: Reply already submitted
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5360)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5401)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:430)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
       at com.kakao.sdk.flutter.KakaoFlutterSdkPlugin.onActivityResult(KakaoFlutterSdkPlugin.kt:201)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:805)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:428)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:807)
       at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:724)
       at android.app.Activity.dispatchActivityResult(Activity.java:8300)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5353)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5401)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.1 22C65 darwin-arm, locale ko-KR)
    • Flutter version 3.3.9 on channel stable at /Users/teddy/Development/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (8 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/teddy/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (5 available)
    • SM N960N (mobile)           • 28898ea46b3f7ece                     • android-arm64  • Android 10 (API 29)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • iPhone 14 Pro Max (mobile)  • 858101B1-D4B5-4CDB-A4F9-855FD832BB36 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2
      (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by Funncy** [comment]
requestCode = 1, resultCode = -1 , data=null로 들어올때 죽습니다

**Comment by Funncy** [comment]
문제를 더 살펴보니
아래 코드에가 Flutter에서 관리하는 onActivityResult Map에 들어가서 onActivityResult함수가 호출될때마다 loop를 돌 고 있습니다.
예측상 requestCode가 1로 들어오는 특정 상황에서 (카카오에서 보내준게 아님)
저 아래 코드가 똑같이 실행되며 result?.success(url)이 호출되어 이미 reply한 결과에 다시 한번 success를 보내서 발생하는 문제로 보입니다.

당장은 data가 없다면 return false 코드를 추가하여 해결하였습니다 PR을 날려도 될까요?

``
 override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?): Boolean {
        if (requestCode == Constants.REQUEST_KAKAO_LOGIN && resultCode == -1) {
            return when (resultCode) {
                Activity.RESULT_OK -> {
                    val url = data?.getStringExtra(Constants.KEY_RETURN_URL)
                    result?.success(url)
                    true
                }
                Activity.RESULT_CANCELED -> {
                    val errorCode = data?.getStringExtra(Constants.KEY_ERROR_CODE) ?: "ERROR"
                    val errorMessage = data?.getStringExtra(Constants.KEY_ERROR_MESSAGE)
                    result?.error(errorCode, errorMessage, null)
                    true
                }
                else -> false
            }
        }
        return false
    }
``

**Comment by mbkim95** [comment]
안녕하세요

이슈 내용 확인했고 수정해서 다음 배포에 포함하도록 하겠습니다.

이슈 제보주셔서 감사합니다

**Comment by mbkim95** [comment]
@Funncy 
안녕하세요 해당 이슈 수정된 1.4.0 버전 배포 완료되었습니다.
제보주셔서 다시 한번 감사드립니다
