### ISSUE TITLE
[Bug] error: misconfigured, error_description: invalid android_key_hash or ios_bundle_id or web_site_url

### ISSUE THREAD

**Issue by howyoujini** [kakao/kakao_flutter_sdk#199]
### 이슈 설명 (Issue description)

카카오 로그인 시, 동의 확인화면 까진 잘 뜨고, 체크후 확인버튼을 클릭하면, 아래에 있는 로그가 뜹니다.

https://github.com/user-attachments/assets/940a7b57-d02b-4c71-85b6-d2f0605773c6

https://github.com/user-attachments/assets/d54c81a2-4062-4c1b-8bbb-0b8054d0904c

로그에 있는 내용을 구글링해보니, KakaoSdk.origin 을 활용해서 android key hash 작성해보라는 issue 를 발견하고, 다시 시도후에도 동일한 로그를 발생시킵니다. ios 환경에서 발생하는 것인지 안드로이드에서 발생하는 현상인지 원인이 추상적이어서 문의드립니다..

참고 이슈
https://github.com/kakao/kakao_flutter_sdk/issues/97
https://github.com/kakao/kakao_flutter_sdk/issues/115

1. 안드로이드 Key hash 등록했습니다.
2. iOS 번들 아이디 공식문서 flutter 를 보고 등록했습니다.

<img width="1350" alt="Screenshot 2024-12-26 at 8 33 14 PM" src="https://github.com/user-attachments/assets/10e0edea-e7b6-4916-8e5d-451b65c4ad02" />

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await dotenv.load(fileName: ".env");

  await resolveDependency();
  KakaoSdk.init(
    javaScriptAppKey: dotenv.get("KAKAO_JS_KEY"),
    nativeAppKey: dotenv.get("KAKAO_NATIVE_KEY"),
  );

  await printKeyHash();
  runApp(const MyApp());
}

Future<void> printKeyHash() async {
  try {
    final keyHash = await KakaoSdk.origin;
    print("현재 사용 중인 키 해시: $keyHash");
  } catch (e) {
    print("키 해시를 가져오는 중 오류 발생: $e");
  }
}
```

또 로그 스택을 확인해보면, ApiFactory.handleApiError (package:kakao_flutter_sdk_common/src/api_factory.dart:38:7) 으로 dio.post 할 때 발생하는 것 같습니다.

### 앱 ID (App ID)

1179590

### 플랫폼 (Platform)

iOS 18.1.1

### 디바이스 (Device)

iPhone 13 mini

### Version

1.9.1+2

### Flutter SDK

3.24.3

### 재현 방법 (Steps to reproduce)

1. 카카오 로그인하기 버튼을 클릭합니다.
2. kakao talk 으로 라우팅이 잘 되고, 동의해야하는 부분에 체크한 후 수락을 클릭합니다.
3. 그 이후, error: misconfigured, error_description: invalid android_key_hash or ios_bundle_id or web_site_url 에러가 로그에 찍힙니다.

### 코드 샘플 (Code Sample)

```dart
Future<KakaoTalkAuthToken> _loginWithKakao(
      final KakaoLoginEvent kakaoLoginEvent) async {
    if (await kakao_sdk.isKakaoTalkInstalled()) {
      Logger().i("카카오로그인");
      final kakao_sdk.OAuthToken token =
          await kakao_sdk.UserApi.instance.loginWithKakaoTalk();

      Logger().i("Social login successful: kakao ${token}");

      return token.let(
          (final kakao_sdk.OAuthToken kakaoOAuthToken) => KakaoTalkAuthToken(
                oAuthToken: kakaoOAuthToken.idToken ?? '',
                accessToken: kakaoOAuthToken.accessToken,
                refreshToken: kakaoOAuthToken.refreshToken ?? '',
              ));
    } else {
      return (await kakao_sdk.UserApi.instance.loginWithKakaoAccount()).let(
          (final kakao_sdk.OAuthToken kakaoOAuthToken) => KakaoTalkAuthToken(
                oAuthToken: kakaoOAuthToken.idToken ?? '',
                accessToken: kakaoOAuthToken.accessToken,
                refreshToken: kakaoOAuthToken.refreshToken ?? '',
              ));
    }
  }
```

### Logs

```shell
flutter: {error: misconfigured, error_description: invalid android_key_hash or ios_bundle_id or web_site_url}
flutter: \^[[38;5;196m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;196m│ {error: misconfigured, error_description: invalid android_key_hash or ios_bundle_id or web_site_url}<…>
flutter: \^[[38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;196m│ #0   ApiFactory.handleApiError (package:kakao_flutter_sdk_common/src/api_factory.dart:38:7)<…>
flutter: \^[[38;5;196m│ #1   <asynchronous suspension><…>
flutter: \^[[38;5;196m│ #2   AuthApi._issueAccessToken (package:kakao_flutter_sdk_auth/src/auth_api.dart:182:12)<…>
flutter: \^[[38;5;196m│ #3   <asynchronous suspension><…>
flutter: \^[[38;5;196m│ #4   AuthApi.issueAccessToken (package:kakao_flutter_sdk_auth/src/auth_api.dart:58:12)<…>
flutter: \^[[38;5;196m│ #5   <asynchronous suspension><…>
flutter: \^[[38;5;196m│ #6   UserApi.loginWithKakaoTalk (package:kakao_flutter_sdk_user/src/user_api.dart:60:19)<…>
flutter: \^[[38;5;196m│ #7   <asynchronous suspension><…>
flutter: \^[[38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;196m│ ⛔ Error during social login<…>
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.1.1 24B91 darwin-arm64, locale en-KR)
    • Flutter version 3.24.3 on channel stable at /Users/howyoujini/Develop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (4 months ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/howyoujini/Library/Android/sdk
    • Platform android-34, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.96.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (5 available)
    • mypad (mobile)            • 00008027-000D71E63EEB002E • ios            • iOS 18.1.1 22B91
    • myphone (mobile)         • 00008110-001A404634F1801E • ios            • iOS 18.1.1 22B91
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.1.1 24B91 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.1.1 24B91 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 131.0.6778.205

[✓] Network resources
    • All expected network resources are available.
```

**Comment by mbkim95** [comment]
안녕하세요

서버 로그 확인해봤을 때 카카오디벨로퍼스에 등록된 bundle_id는 `***.***.******` 이고, 실제 앱에 설정된 bundle_id는 `***.***.***a***`로, 실제 앱에 설정된 bundle_id에는 중간에 a 가 추가되어있습니다. (혹시 몰라서 bundle_id 값은 마스킹처리했습니다)

bundle_id 값 확인하셔서 다시 등록하시면 정상적으로 동작할 것으로 보여요. 확인 및 수정 부탁드리겠습니다.
