### ISSUE TITLE
특정 안드로이드 폰에서 크래시

### ISSUE THREAD

**Issue by hvasc** [kakao/kakao_flutter_sdk#35]
안녕하세요 kakao_flutter_sdk를 통해 카카오 로그인을 구현해서 서비스중입니다.
특정 폰에서 이런 에러 로그가 남아서 문의드립니다.
뭔가 설정이 잘못된걸까요?

Caused by java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.e.b$a.a(:35)
       at e.b.b.a.j$a$a.a(:14)
       at com.kakao.sdk.flutter.TalkAuthCodeActivity.onActivityResult(:58)
       at android.app.Activity.dispatchActivityResult(Activity.java:8120)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4983)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5031)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2063)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7615)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

**Comment by CoderSpinoza** [comment]
특정 폰이 어떤 모델인지 혹시 조금 더 정보를 주실 수 있을까요?

**Comment by hvasc** [comment]
> 특정 폰이 어떤 모델인지 혹시 조금 더 정보를 주실 수 있을까요?

Android 10 / Galaxy S10 5G 모델이었습니다. 
테스트 장비로 해당 모델이 있는데 재현이 안되고 특정 고객만 항상 발생했습니다.
