### ISSUE TITLE
PlatformException: No browser supports custom tabs protocol on this device

### ISSUE THREAD

**Issue by jeiea** [kakao/kakao_flutter_sdk#65]
Galaxy Note20 5G, 
Galaxy S10e에서 아래 에러가 나는 것을 수집했습니다. 진단삼아 크롬 브라우저가 설치가 안 되어 있는 것인지 사용자에게 질문해봤는데 크롬과 카카오톡 둘 다 설치가 되어있다고 답변을 받았습니다.

에러가 나지 않을 것 같은 상황인데 혹시 문제 발생 원인으로 짐작가는 부분이 있는지 질문드립니다.

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(EUNKNOWN, No browser supports custom tabs protocol on this device., null, null)
       at StandardMethodCodec.decodeEnvelope(StandardMethodCodec.java:581)
       at MethodChannel._invokeMethod(MethodChannel.java:158)
       at ._asyncErrorWrapperHelper(.java)
```

```dart
  Future<AccessTokenResponse> _requestAccessToken() async {
    KakaoContext.clientId = Flavor.KAKAO_APP_KEY;

    try {
      var refreshedToken = await _tryTokenRefresh();
      if (refreshedToken != null) {
        return refreshedToken;
      }
    } catch (error) {
      // ignore, it's just trial
    }

    final isInstalled = await isKakaoTalkInstalled();
    final scopes = [
      'profile',
      'account_email',
      if (Flavor.FLAVOR == 'production') ...['plusfriends', 'phone_number']
    ];
    final authCode = isInstalled
        ? await AuthCodeClient.instance.requestWithTalk(scopes: scopes)
        : await AuthCodeClient.instance.request(scopes: scopes);
    final token = await AuthApi.instance.issueAccessToken(authCode);
    return token;
  }

  Future<AccessTokenResponse> _tryTokenRefresh() async {
    final storedToken = await AccessTokenStore.instance.fromStore();
    if (storedToken.refreshToken == null) {
      return null;
    }
    return AuthApi.instance.refreshAccessToken(storedToken.refreshToken);
  }
```

**Comment by jeiea** [comment]
[package visibility](https://stackoverflow.com/a/62856745) 문제로 드러났습니다. 이슈는 닫습니다.
